# Generated by Django 3.2 on 2022-11-01 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='accepted',
        ),
    ]
