# Generated by Django 3.2 on 2022-11-01 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='item_id')),
                ('name', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='items')),
                ('point', models.IntegerField(default=10)),
                ('category', models.CharField(choices=[('item1', 'item1'), ('item2', 'item2'), ('badge', 'badge')], default='N', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.item')),
            ],
        ),
    ]
