# Generated by Django 3.2 on 2022-10-03 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='item_id')),
                ('item_name', models.CharField(default='item', max_length=45, verbose_name='item_name')),
                ('image', models.ImageField(upload_to='items')),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('space_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='space_id')),
                ('category_1', models.ForeignKey(db_column='category_1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_1', to='space.item')),
                ('category_2', models.ForeignKey(db_column='category_2', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_2', to='space.item')),
                ('category_3', models.ForeignKey(db_column='category_3', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_3', to='space.item')),
                ('category_4', models.ForeignKey(db_column='category_4', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_4', to='space.item')),
                ('owner', models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, related_name='owner_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
