# Generated by Django 3.2 on 2022-10-03 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='item_id')),
                ('image', models.ImageField(upload_to='items')),
                ('point', models.IntegerField(default=10)),
                ('item_category', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('space_id', models.BigAutoField(primary_key=True, serialize=False, unique=True, verbose_name='space_id')),
            ],
        ),
    ]
