# Generated by Django 3.2 on 2022-10-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='item_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='space',
            old_name='space_id',
            new_name='id',
        ),
    ]
