# Generated by Django 3.2 on 2022-10-11 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('space', '0003_auto_20221004_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buy',
            name='pick',
        ),
        migrations.AddField(
            model_name='space',
            name='item1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_item1', to='space.item'),
        ),
        migrations.AddField(
            model_name='space',
            name='item2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_item2', to='space.item'),
        ),
        migrations.AddField(
            model_name='space',
            name='item3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='space_item3', to='space.item'),
        ),
        migrations.AlterField(
            model_name='space',
            name='owner',
            field=models.ForeignKey(db_column='owner', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
