# Generated by Django 3.2 on 2022-10-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0004_auto_20221011_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('item1', 'item1'), ('item2', 'item2'), ('badge', 'badge')], default='N', max_length=200),
        ),
        migrations.DeleteModel(
            name='Space',
        ),
    ]
