# Generated by Django 3.2 on 2022-10-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space', '0005_auto_20221011_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='pick',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
