# Generated by Django 3.2 on 2022-10-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('product_no', models.IntegerField()),
                ('purpose', models.CharField(max_length=200)),
            ],
        ),
    ]
